version: "3"
networks:
  luby-cash:
    external: true
  luby-cash-ms:
    driver: bridge

services:
  app:
    container_name: 'luby-cash-ms-express'
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    image: luby-cash-ms-express
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - luby-cash
      - luby-cash-ms
    ports:
      - '3334:3334'

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 126453
      POSTGRES_DB: db_luby_cash_ms
    ports:
      - '5432:5432'
    networks:
      - luby-cash-ms
    volumes:
       - /db/var/lib/postgres